/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leitor.numero.pensamento;

/**
 *
 * @author User
 */
public class TelaAdivinhacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdivinhacao.class.getName());

    /**
     * Creates new form TelaAdivinhacao
     */
    public TelaAdivinhacao() {
        initComponents();
        lblResp.setText("<html><center>Vou pensar em um valor entre 1 e 5.<br>Tente advinhar</center></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spnNum = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResp.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResp.setText("<vazio>");
        getContentPane().add(lblResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 71, 320, 170));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pngwing.com.png"))); // NOI18N
        jLabel3.setToolTipText("asdad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kindpng_4647402.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        spnNum.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        spnNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 480, 100, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        // TODO add your handling code here:
        double n = (Math.random() * 5) + 1;
        int num_pc = (int) n;
        int num_user = Integer.parseInt(spnNum.getValue().toString());
        String resultado = (num_user == num_pc)?"<html>Acertou!</html>":"<html><center>Errou!<br>O numero era " + num_pc + "</center></html>";
        lblResp.setText(resultado);
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdivinhacao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResp;
    private javax.swing.JSpinner spnNum;
    // End of variables declaration//GEN-END:variables
}
